name: TheBridges
author: RDNachoz
main: RDNachoz.plugins.bridges.Bridges
softdepend: [Multiverse-Core, Multiworld, DimensionDoor]
version: 1.1.0.1
depend: [TagAPI]
softdepend: [Multiverse-Core, Multiworld, DimensionDoor]
load: POSTWORLD
commands:
  bb:
    usage: /<command>
    description: The Main BukkitBridges Command!
permissions:
  bb.create:
    description: Allows you to create and edit arenas
    default: op
  bb.delete:
    description: Allows you to delete unwanted arenas
    default: op
  bb.start:
    description: Allows you to force start an arena
    default: op
  bb.join:
    description: Allows you to join and use arenas
    default: true
  bb.signjoin:
    description: Allows you to join by clicking a sign
    default: true
  bb.leave:
    description: Allows you to leave Bridges arenas
    default: true
  bb.info:
    description: Allows you to see the infomation about an arena
    default: op